apiVersion: v1
kind: ReplicaSet
metadata:
  name: replica-webapp
  namespace: ns-webapp
  labels:
    app: mysql
spec:
  template:
    metadata:
      name: pod-mysql
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-con
        image: 711386944025.dkr.ecr.us-east-1.amazonaws.com/clo835-assign1-mysql-ecr:latest
  replicas: 1
  selector:
    matchLabels:
      app: mysql