apiVersion: v1
kind: Pod
metadata:
  name: pod-webapp
  namespace: ns-webapp
  labels:
    app: employees
spec:
  containers:
  - image: 711386944025.dkr.ecr.us-east-1.amazonaws.com/clo835-assign1-webapp-ecr:latest
    name: cont-webapp
    ports:
    - containerPort: 8080
      protocol: TCP