apiVersion: v1
kind: ReplicaSet
metadata:
  name: replica-webapp
  namespace: ns-webapp
  labels:
    app: employees
spec:
  template:
    metadata:
      name: pod-webapp
      labels:
        app: employees
    spec:
      containers:
      - name: webapp-cont
        image: 711386944025.dkr.ecr.us-east-1.amazonaws.com/clo835-assign1-webapp-ecr:v0.1
  replicas: 3
  selector:
    matchLabels:
      app: employees