apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-webapp
  namespace: ns-webapp
  labels:
    app: employees
spec:
  template:
    metadata:
      name: pod-webapp
      labels:
        app: employees
    spec:
      containers:
      - name: cont-webapp
        image: 711386944025.dkr.ecr.us-east-1.amazonaws.com/clo835-assign1-webapp-ecr:v0.1
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: DBHOST
          value: "10.244.0.5"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DATABASE
          value: "employees"
        - name: DBPWD
          value: "pw"
  replicas: 3
  selector:
    matchLabels:
      app: employees
